project:
  type: website
  output-dir: docs
  preview: 
    port: 3744
    browser: true

website:
  title: "Oleson Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house-door-fill
      - href: team.qmd
        text: Team
        icon: people-fill
      - href: research.qmd
        text: Research
        icon: search
      - href: publications.qmd
        text: Publications
        icon: book-fill
      - href: data.qmd
        text: Data
        icon: bar-chart-line-fill
      # - href: contact.qmd
      #   text: Contact
      #   icon: telephone-fill
    right:
      - icon: envelope-fill
        href: mailto:koleson@hawaii.edu
      - icon: github
        href: https://github.com/olesonlab
      - icon: twitter-x
        href: https://twitter.com/@Olesonlab
    foreground: rgba(232, 232, 232, 0.95)
    background: rgba(0, 126, 147, 0.55)
  page-footer: 
    foreground: rgba(232, 232, 232, 0.95)
    background: rgba(0, 126, 147, 0.55)
    right: |
      <strong>Oleson Lab</strong><br>
      <strong>Follow Us</strong>:
      [{{< bi github >}}](https://github.com/olesonlab)
      [{{< bi twitter-x >}}](https://twitter.com/@Olesonlab)
      <br>
      <strong>Quick Links</strong>: 
      [{{< bi people-fill >}}](https://olesonlab.github.io/team.html)
      [{{< bi search >}}](https://olesonlab.github.io/research.html)
      [{{< bi book-fill >}}](https://olesonlab.github.io/publications.html)
      [{{< bi bar-chart-line-fill >}}](https://olesonlab.github.io/data.html)
    left: |
      <strong>Contact Us</strong>: <br>
      808-956-8864 |
      koleson@hawaii.edu <br>
      Sherman Lab 109, 1910 East West Road, Honolulu, HI 96822

    center: |
      <br><br>© 2024 Oleson Lab, University of Hawaii at Manoa 
  back-to-top-navigation: true
  open-graph: 
    site-name: "Oleson Lab Website"
  

format:
  html:
    theme: [litera, assets/styles/styles.scss]
    fontsize: 12pt
    page-layout: full
    link-external-newwindow: true
    toc: true
    
execute: 
  freeze: auto



